services:
  parser-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./output/parser_service/parsed:/app/output/parser_service/parsed
      - ./output/parser_service/uploads:/app/output/parser_service/uploads
